# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: cd /workspace/Odyssey && sudo cp $PWD/Scripts/git-cinnabar $PWD/Scripts/git-remote-hg /usr/bin && sudo chmod +x /usr/bin/git-cinnabar /usr/bin/git-remote-hg && git fetch mozilla
  - name: Installers
    command: sudo apt update && /workspace/Odyssey/mach bootstrap

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
