# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Mozilla Fetcher # runs during prebuild
    command: sudo cp /workspace/Odyssey/Scripts/git-cinnabar/git-cinnabar /workspace/Odyssey/Scripts/git-cinnabar/git-remote-hg /usr/bin && sudo chmod +x /usr/bin/git-remote-hg /usr/bin/git-cinnabar && cd /workspace/Odyssey/ && git pull mozilla bookmarks/central
  - name: 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
