# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_LINUX=1 -DOS_ARCH=Linux -DMOZ_WIDGET_TOOLKIT=gtk -DMOZ_SERVICES_SYNC -DMOZ_BUILD_APP_IS_BROWSER
DIRS := test/gtest
include $(topsrcdir)/config/AB_rCD.mk
EXPORT_TARGETS += init/$(MDDEPDIR)/StaticPrefListAll.h.stub
init/StaticPrefListAll.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefsAll.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_accessibility.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_alerts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_apz.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_beacon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_bidi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_browser.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_canvas.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_channelclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_clipboard.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_content.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_converter.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_cookiebanners.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_datareporting.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_device.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_devtools.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_docshell.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_dom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_editor.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_extensions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_fission.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_font.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_full_screen_api.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_general.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_geo.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_gfx.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_gl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_html5.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_idle_period.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_image.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_intl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_javascript.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_layers.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_layout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_mathml.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_media.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_midi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_mousewheel.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_mozilla.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_network.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_nglayout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_page_load.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_pdfjs.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_permissions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_plain_text.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_plugin.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_plugins.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_preferences.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_print.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_privacy.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_prompts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_security.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_signon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_slider.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_storage.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_svg.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_telemetry.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_test.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_threads.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_timer.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_toolkit.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_ui.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_urlclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_view_source.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_webgl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_widget.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefList_zoom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_accessibility.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_alerts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_apz.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_beacon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_bidi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_browser.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_canvas.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_channelclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_clipboard.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_content.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_converter.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_cookiebanners.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_datareporting.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_device.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_devtools.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_docshell.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_dom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_editor.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_extensions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_fission.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_font.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_full_screen_api.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_general.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_geo.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_gfx.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_gl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_html5.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_idle_period.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_image.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_intl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_javascript.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_layers.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_layout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_mathml.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_media.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_midi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_mousewheel.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_mozilla.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_network.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_nglayout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_page_load.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_pdfjs.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_permissions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_plain_text.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_plugin.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_plugins.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_preferences.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_print.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_privacy.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_prompts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_security.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_signon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_slider.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_storage.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_svg.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_telemetry.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_test.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_threads.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_timer.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_toolkit.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_ui.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_urlclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_view_source.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_webgl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_widget.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
StaticPrefs_zoom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
init/StaticPrefsCGetters.cpp: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
static_prefs.rs: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
EXTRA_MDDEPEND_FILES += init/$(MDDEPDIR)/StaticPrefListAll.h.pp
init/$(MDDEPDIR)/StaticPrefListAll.h.stub: /workspace/Odyssey/src/modules/libpref/init/generate_static_pref_list.py $(srcdir)/init/StaticPrefList.yaml
	$(REPORT_BUILD)
	$(call py_action,file_generate,/workspace/Odyssey/src/modules/libpref/init/generate_static_pref_list.py emit_code init/StaticPrefListAll.h init/$(MDDEPDIR)/StaticPrefListAll.h.pp init/$(MDDEPDIR)/StaticPrefListAll.h.stub $(srcdir)/init/StaticPrefList.yaml)
	@$(TOUCH) $@

LOCAL_INCLUDES += -I$(topobjdir)/ipc/ipdl/_ipdlheaders
LOCAL_INCLUDES += -I$(topsrcdir)/ipc/chromium/src

# We build files in 'unified' mode by including several files
# together into a single source file.  This cuts down on
# compilation times and debug information size.
UNIFIED_CPPSRCS := Unified_cpp_modules_libpref0.cpp
CPPSRCS += $(UNIFIED_CPPSRCS)
dist_include_mozilla_FILES += init/StaticPrefList_accessibility.h
dist_include_mozilla_FILES += init/StaticPrefList_alerts.h
dist_include_mozilla_FILES += init/StaticPrefList_apz.h
dist_include_mozilla_FILES += init/StaticPrefList_beacon.h
dist_include_mozilla_FILES += init/StaticPrefList_bidi.h
dist_include_mozilla_FILES += init/StaticPrefList_browser.h
dist_include_mozilla_FILES += init/StaticPrefList_canvas.h
dist_include_mozilla_FILES += init/StaticPrefList_channelclassifier.h
dist_include_mozilla_FILES += init/StaticPrefList_clipboard.h
dist_include_mozilla_FILES += init/StaticPrefList_content.h
dist_include_mozilla_FILES += init/StaticPrefList_converter.h
dist_include_mozilla_FILES += init/StaticPrefList_cookiebanners.h
dist_include_mozilla_FILES += init/StaticPrefList_datareporting.h
dist_include_mozilla_FILES += init/StaticPrefList_device.h
dist_include_mozilla_FILES += init/StaticPrefList_devtools.h
dist_include_mozilla_FILES += init/StaticPrefList_docshell.h
dist_include_mozilla_FILES += init/StaticPrefList_dom.h
dist_include_mozilla_FILES += init/StaticPrefList_editor.h
dist_include_mozilla_FILES += init/StaticPrefList_extensions.h
dist_include_mozilla_FILES += init/StaticPrefList_fission.h
dist_include_mozilla_FILES += init/StaticPrefList_font.h
dist_include_mozilla_FILES += init/StaticPrefList_full_screen_api.h
dist_include_mozilla_FILES += init/StaticPrefList_general.h
dist_include_mozilla_FILES += init/StaticPrefList_geo.h
dist_include_mozilla_FILES += init/StaticPrefList_gfx.h
dist_include_mozilla_FILES += init/StaticPrefList_gl.h
dist_include_mozilla_FILES += init/StaticPrefList_html5.h
dist_include_mozilla_FILES += init/StaticPrefList_idle_period.h
dist_include_mozilla_FILES += init/StaticPrefList_image.h
dist_include_mozilla_FILES += init/StaticPrefList_intl.h
dist_include_mozilla_FILES += init/StaticPrefList_javascript.h
dist_include_mozilla_FILES += init/StaticPrefList_layers.h
dist_include_mozilla_FILES += init/StaticPrefList_layout.h
dist_include_mozilla_FILES += init/StaticPrefList_mathml.h
dist_include_mozilla_FILES += init/StaticPrefList_media.h
dist_include_mozilla_FILES += init/StaticPrefList_midi.h
dist_include_mozilla_FILES += init/StaticPrefList_mousewheel.h
dist_include_mozilla_FILES += init/StaticPrefList_mozilla.h
dist_include_mozilla_FILES += init/StaticPrefList_network.h
dist_include_mozilla_FILES += init/StaticPrefList_nglayout.h
dist_include_mozilla_FILES += init/StaticPrefList_page_load.h
dist_include_mozilla_FILES += init/StaticPrefList_pdfjs.h
dist_include_mozilla_FILES += init/StaticPrefList_permissions.h
dist_include_mozilla_FILES += init/StaticPrefList_plain_text.h
dist_include_mozilla_FILES += init/StaticPrefList_plugin.h
dist_include_mozilla_FILES += init/StaticPrefList_plugins.h
dist_include_mozilla_FILES += init/StaticPrefList_preferences.h
dist_include_mozilla_FILES += init/StaticPrefList_print.h
dist_include_mozilla_FILES += init/StaticPrefList_privacy.h
dist_include_mozilla_FILES += init/StaticPrefList_prompts.h
dist_include_mozilla_FILES += init/StaticPrefList_security.h
dist_include_mozilla_FILES += init/StaticPrefList_signon.h
dist_include_mozilla_FILES += init/StaticPrefList_slider.h
dist_include_mozilla_FILES += init/StaticPrefList_storage.h
dist_include_mozilla_FILES += init/StaticPrefList_svg.h
dist_include_mozilla_FILES += init/StaticPrefList_telemetry.h
dist_include_mozilla_FILES += init/StaticPrefList_test.h
dist_include_mozilla_FILES += init/StaticPrefList_threads.h
dist_include_mozilla_FILES += init/StaticPrefList_timer.h
dist_include_mozilla_FILES += init/StaticPrefList_toolkit.h
dist_include_mozilla_FILES += init/StaticPrefList_ui.h
dist_include_mozilla_FILES += init/StaticPrefList_urlclassifier.h
dist_include_mozilla_FILES += init/StaticPrefList_view_source.h
dist_include_mozilla_FILES += init/StaticPrefList_webgl.h
dist_include_mozilla_FILES += init/StaticPrefList_widget.h
dist_include_mozilla_FILES += init/StaticPrefList_zoom.h
dist_include_mozilla_FILES += init/StaticPrefListAll.h
dist_include_mozilla_FILES += StaticPrefs_accessibility.h
dist_include_mozilla_FILES += StaticPrefs_alerts.h
dist_include_mozilla_FILES += StaticPrefs_apz.h
dist_include_mozilla_FILES += StaticPrefs_beacon.h
dist_include_mozilla_FILES += StaticPrefs_bidi.h
dist_include_mozilla_FILES += StaticPrefs_browser.h
dist_include_mozilla_FILES += StaticPrefs_canvas.h
dist_include_mozilla_FILES += StaticPrefs_channelclassifier.h
dist_include_mozilla_FILES += StaticPrefs_clipboard.h
dist_include_mozilla_FILES += StaticPrefs_content.h
dist_include_mozilla_FILES += StaticPrefs_converter.h
dist_include_mozilla_FILES += StaticPrefs_cookiebanners.h
dist_include_mozilla_FILES += StaticPrefs_datareporting.h
dist_include_mozilla_FILES += StaticPrefs_device.h
dist_include_mozilla_FILES += StaticPrefs_devtools.h
dist_include_mozilla_FILES += StaticPrefs_docshell.h
dist_include_mozilla_FILES += StaticPrefs_dom.h
dist_include_mozilla_FILES += StaticPrefs_editor.h
dist_include_mozilla_FILES += StaticPrefs_extensions.h
dist_include_mozilla_FILES += StaticPrefs_fission.h
dist_include_mozilla_FILES += StaticPrefs_font.h
dist_include_mozilla_FILES += StaticPrefs_full_screen_api.h
dist_include_mozilla_FILES += StaticPrefs_general.h
dist_include_mozilla_FILES += StaticPrefs_geo.h
dist_include_mozilla_FILES += StaticPrefs_gfx.h
dist_include_mozilla_FILES += StaticPrefs_gl.h
dist_include_mozilla_FILES += StaticPrefs_html5.h
dist_include_mozilla_FILES += StaticPrefs_idle_period.h
dist_include_mozilla_FILES += StaticPrefs_image.h
dist_include_mozilla_FILES += StaticPrefs_intl.h
dist_include_mozilla_FILES += StaticPrefs_javascript.h
dist_include_mozilla_FILES += StaticPrefs_layers.h
dist_include_mozilla_FILES += StaticPrefs_layout.h
dist_include_mozilla_FILES += StaticPrefs_mathml.h
dist_include_mozilla_FILES += StaticPrefs_media.h
dist_include_mozilla_FILES += StaticPrefs_midi.h
dist_include_mozilla_FILES += StaticPrefs_mousewheel.h
dist_include_mozilla_FILES += StaticPrefs_mozilla.h
dist_include_mozilla_FILES += StaticPrefs_network.h
dist_include_mozilla_FILES += StaticPrefs_nglayout.h
dist_include_mozilla_FILES += StaticPrefs_page_load.h
dist_include_mozilla_FILES += StaticPrefs_pdfjs.h
dist_include_mozilla_FILES += StaticPrefs_permissions.h
dist_include_mozilla_FILES += StaticPrefs_plain_text.h
dist_include_mozilla_FILES += StaticPrefs_plugin.h
dist_include_mozilla_FILES += StaticPrefs_plugins.h
dist_include_mozilla_FILES += StaticPrefs_preferences.h
dist_include_mozilla_FILES += StaticPrefs_print.h
dist_include_mozilla_FILES += StaticPrefs_privacy.h
dist_include_mozilla_FILES += StaticPrefs_prompts.h
dist_include_mozilla_FILES += StaticPrefs_security.h
dist_include_mozilla_FILES += StaticPrefs_signon.h
dist_include_mozilla_FILES += StaticPrefs_slider.h
dist_include_mozilla_FILES += StaticPrefs_storage.h
dist_include_mozilla_FILES += StaticPrefs_svg.h
dist_include_mozilla_FILES += StaticPrefs_telemetry.h
dist_include_mozilla_FILES += StaticPrefs_test.h
dist_include_mozilla_FILES += StaticPrefs_threads.h
dist_include_mozilla_FILES += StaticPrefs_timer.h
dist_include_mozilla_FILES += StaticPrefs_toolkit.h
dist_include_mozilla_FILES += StaticPrefs_ui.h
dist_include_mozilla_FILES += StaticPrefs_urlclassifier.h
dist_include_mozilla_FILES += StaticPrefs_view_source.h
dist_include_mozilla_FILES += StaticPrefs_webgl.h
dist_include_mozilla_FILES += StaticPrefs_widget.h
dist_include_mozilla_FILES += StaticPrefs_zoom.h
dist_include_mozilla_FILES += StaticPrefsAll.h
dist_include_mozilla_DEST := $(DEPTH)/dist/include/mozilla
dist_include_mozilla_TARGET := export
INSTALL_TARGETS += dist_include_mozilla
DIST_FILES_0 += $(srcdir)/greprefs.js
DIST_FILES_0_PATH := $(DEPTH)/dist/bin/
DIST_FILES_0_TARGET := misc
PP_TARGETS += DIST_FILES_0
COMPUTED_LDFLAGS += -lpthread -fuse-ld=lld -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/lib/x86_64-linux-gnu -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -Wl,-O0 -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,-z,nocopyreloc -Wl,-Bsymbolic-functions -fstack-protector-strong -fstack-clash-protection -Wl,-rpath-link,/workspace/Odyssey/dist/bin -Wl,-rpath-link,/usr/local/lib
LIBRARY_NAME := modules_libpref
FORCE_STATIC_LIB := 1
REAL_LIBRARY := libmodules_libpref.a
DEFINES += -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API
COMPUTED_CFLAGS += -I/workspace/Odyssey/dist/system_wrappers -include /workspace/Odyssey/src/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_LINUX=1 -DOS_ARCH=Linux -DMOZ_WIDGET_TOOLKIT=gtk -DMOZ_SERVICES_SYNC -DMOZ_BUILD_APP_IS_BROWSER -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/workspace/Odyssey/src/modules/libpref -I/workspace/Odyssey/modules/libpref -I/workspace/Odyssey/ipc/ipdl/_ipdlheaders -I/workspace/Odyssey/src/ipc/chromium/src -I/workspace/Odyssey/dist/include -I/workspace/Odyssey/dist/include/nspr -I/workspace/Odyssey/dist/include/nss -include /workspace/Odyssey/mozilla-config.h -DMOZILLA_CLIENT -fPIC -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wbitfield-enum-conversion -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wclass-varargs -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wenum-compare-conditional -Wenum-float-conversion -Wstring-conversion -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Werror=implicit-function-declaration -Wno-psabi -Wthread-safety -Wno-unknown-warning-option -fno-strict-aliasing -ffp-contract=off
COMPUTED_CXXFLAGS += -I/workspace/Odyssey/dist/stl_wrappers -I/workspace/Odyssey/dist/system_wrappers -include /workspace/Odyssey/src/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_LINUX=1 -DOS_ARCH=Linux -DMOZ_WIDGET_TOOLKIT=gtk -DMOZ_SERVICES_SYNC -DMOZ_BUILD_APP_IS_BROWSER -DMOZ_HAS_MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DSTATIC_EXPORTABLE_JS_API -I/workspace/Odyssey/src/modules/libpref -I/workspace/Odyssey/modules/libpref -I/workspace/Odyssey/ipc/ipdl/_ipdlheaders -I/workspace/Odyssey/src/ipc/chromium/src -I/workspace/Odyssey/dist/include -I/workspace/Odyssey/dist/include/nspr -I/workspace/Odyssey/dist/include/nss -DMOZILLA_CLIENT -include /workspace/Odyssey/mozilla-config.h -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fPIC -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wbitfield-enum-conversion -Wdeprecated-this-capture -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wno-invalid-offsetof -Wclass-varargs -Wempty-init-stmt -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wc++2a-compat -Wenum-compare-conditional -Wenum-float-conversion -Wno-ambiguous-reversed-operator -Wno-error=deprecated -Wno-error=deprecated-anon-enum-enum-conversion -Wno-error=deprecated-enum-enum-conversion -Wno-error=deprecated-pragma -Wno-error=deprecated-this-capture -Wcomma -Wimplicit-fallthrough -Wstring-conversion -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Wno-psabi -Wthread-safety -Wno-unknown-warning-option -fno-strict-aliasing -ffp-contract=off
COMPUTED_CXX_LDFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fPIC -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables
COMPUTED_C_LDFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -fPIC -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables
NONRECURSIVE_TARGETS += export
NONRECURSIVE_TARGETS_export += xpidl
NONRECURSIVE_TARGETS_export_xpidl_DIRECTORY = $(DEPTH)/xpcom/xpidl
NONRECURSIVE_TARGETS_export_xpidl_TARGETS += export
