# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DMOZ_HAS_MOZGLUE -DNSS_USE_STATIC_LIBS
LOCAL_INCLUDES += -I$(topsrcdir)/security/nss/lib/ssl
LOCAL_INCLUDES += -I$(topsrcdir)/security/manager/ssl/tests/unit/tlsserver/lib
CPPSRCS += $(srcdir)/BadCertAndPinningServer.cpp
CPPSRCS += $(srcdir)/DelegatedCredentialsServer.cpp
CPPSRCS += $(srcdir)/EncryptedClientHelloServer.cpp
CPPSRCS += $(srcdir)/FaultyServer.cpp
CPPSRCS += $(srcdir)/GenerateOCSPResponse.cpp
CPPSRCS += $(srcdir)/OCSPStaplingServer.cpp
CPPSRCS += $(srcdir)/SanctionsTestServer.cpp
COMPUTED_LDFLAGS += -lpthread -fuse-ld=lld -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/lib/x86_64-linux-gnu -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -Wl,-O0 -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,-z,nocopyreloc -Wl,-Bsymbolic-functions -fstack-protector-strong -fstack-clash-protection -rdynamic -Wl,-rpath-link,/workspace/Odyssey/dist/bin -Wl,-rpath-link,/usr/local/lib
COMPUTED_CFLAGS += -I/workspace/Odyssey/dist/system_wrappers -include /workspace/Odyssey/src/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -DNDEBUG=1 -DTRIMMED=1 -DMOZ_HAS_MOZGLUE -DNSS_USE_STATIC_LIBS -I/workspace/Odyssey/src/security/manager/ssl/tests/unit/tlsserver/cmd -I/workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd -I/workspace/Odyssey/src/security/nss/lib/ssl -I/workspace/Odyssey/src/security/manager/ssl/tests/unit/tlsserver/lib -I/workspace/Odyssey/dist/include -I/workspace/Odyssey/dist/include/nspr -I/workspace/Odyssey/dist/include/nss -include /workspace/Odyssey/mozilla-config.h -DMOZILLA_CLIENT -fPIC -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wbitfield-enum-conversion -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wclass-varargs -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wenum-compare-conditional -Wenum-float-conversion -Wstring-conversion -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Werror=implicit-function-declaration -Wno-psabi -Wthread-safety -Wno-unknown-warning-option -fno-strict-aliasing -ffp-contract=off
COMPUTED_CXXFLAGS += -I/workspace/Odyssey/dist/stl_wrappers -I/workspace/Odyssey/dist/system_wrappers -include /workspace/Odyssey/src/config/gcc_hidden.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -DNDEBUG=1 -DTRIMMED=1 -DMOZ_HAS_MOZGLUE -DNSS_USE_STATIC_LIBS -I/workspace/Odyssey/src/security/manager/ssl/tests/unit/tlsserver/cmd -I/workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd -I/workspace/Odyssey/src/security/nss/lib/ssl -I/workspace/Odyssey/src/security/manager/ssl/tests/unit/tlsserver/lib -I/workspace/Odyssey/dist/include -I/workspace/Odyssey/dist/include/nspr -I/workspace/Odyssey/dist/include/nss -DMOZILLA_CLIENT -include /workspace/Odyssey/mozilla-config.h -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fPIC -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables -Wall -Wbitfield-enum-conversion -Wdeprecated-this-capture -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wno-invalid-offsetof -Wclass-varargs -Wempty-init-stmt -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wc++2a-compat -Wenum-compare-conditional -Wenum-float-conversion -Wno-ambiguous-reversed-operator -Wno-error=deprecated -Wno-error=deprecated-anon-enum-enum-conversion -Wno-error=deprecated-enum-enum-conversion -Wno-error=deprecated-pragma -Wno-error=deprecated-this-capture -Wcomma -Wimplicit-fallthrough -Wstring-conversion -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Wno-psabi -Wthread-safety -Wno-unknown-warning-option -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gtk-3.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pango-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/cairo -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pixman-1 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/libpng12 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gdk-pixbuf-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gio-unix-2.0/ -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/harfbuzz -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/atk-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi2-atk/2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/dbus-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gtk-3.0/unix-print -pthread -fno-strict-aliasing -ffp-contract=off
COMPUTED_CXX_LDFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -fno-sized-deallocation -fno-aligned-new -fno-exceptions -fPIC -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables
COMPUTED_C_LDFLAGS += -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection -fPIC -fno-math-errno -pthread -pipe -gdwarf-4 -O2 -fno-omit-frame-pointer -funwind-tables
SIMPLE_PROGRAMS += BadCertAndPinningServer
BadCertAndPinningServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/BadCertAndPinningServer.list
BadCertAndPinningServer: BadCertAndPinningServer.list
BadCertAndPinningServer: BadCertAndPinningServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SHARED_LIBS += ../../../../../../../config/external/nspr/pr/libnspr4.so
SHARED_LIBS += ../../../../../../../config/external/nspr/libc/libplc4.so
SHARED_LIBS += ../../../../../../../config/external/nspr/ds/libplds4.so
SHARED_LIBS += ../../../../../../nss/lib/softoken/softoken_softokn3/libsoftokn3.so
SHARED_LIBS += ../../../../../../../config/external/sqlite/libmozsqlite3.so
SHARED_LIBS += ../../../../../../nss/lib/util/util_nssutil3/libnssutil3.so
OS_LIBS += -lpthread
OS_LIBS += -ldl
OS_LIBS += -lc
SIMPLE_PROGRAMS += DelegatedCredentialsServer
DelegatedCredentialsServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/DelegatedCredentialsServer.list
DelegatedCredentialsServer: DelegatedCredentialsServer.list
DelegatedCredentialsServer: DelegatedCredentialsServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SIMPLE_PROGRAMS += EncryptedClientHelloServer
EncryptedClientHelloServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/EncryptedClientHelloServer.list
EncryptedClientHelloServer: EncryptedClientHelloServer.list
EncryptedClientHelloServer: EncryptedClientHelloServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SIMPLE_PROGRAMS += FaultyServer
FaultyServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/FaultyServer.list
FaultyServer: FaultyServer.list
FaultyServer: FaultyServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SIMPLE_PROGRAMS += GenerateOCSPResponse
GenerateOCSPResponse_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/GenerateOCSPResponse.list
GenerateOCSPResponse: GenerateOCSPResponse.list
GenerateOCSPResponse: GenerateOCSPResponse.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SIMPLE_PROGRAMS += OCSPStaplingServer
OCSPStaplingServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/OCSPStaplingServer.list
OCSPStaplingServer: OCSPStaplingServer.list
OCSPStaplingServer: OCSPStaplingServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
SIMPLE_PROGRAMS += SanctionsTestServer
SanctionsTestServer_OBJS := /workspace/Odyssey/security/manager/ssl/tests/unit/tlsserver/cmd/SanctionsTestServer.list
SanctionsTestServer: SanctionsTestServer.list
SanctionsTestServer: SanctionsTestServer.o \
    ../../../../../../../mozglue/build/dummy.o \
    ../../../../../../../memory/build/Unified_cpp_memory_build0.o \
    ../../../../../../../memory/replace/logalloc/FdPrintf.o \
    ../../../../../../../memory/replace/logalloc/LogAlloc.o \
    ../../../../../../../memory/replace/dmd/Unified_cpp_memory_replace_dmd0.o \
    ../../../../../../../memory/replace/phc/Unified_cpp_memory_replace_phc0.o \
    ../../../../../../../memory/mozalloc/cxxalloc.o \
    ../../../../../../../memory/mozalloc/Unified_cpp_memory_mozalloc0.o \
    ../../../../../../../mozglue/interposers/Unified_cpp_mozglue_interposers0.o \
    ../../../../../../../mozglue/baseprofiler/shared-libraries-linux.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler0.o \
    ../../../../../../../mozglue/baseprofiler/Unified_cpp_mozglue_baseprofiler1.o \
    ../../../../../../../mozglue/misc/AutoProfilerLabel.o \
    ../../../../../../../mozglue/misc/AwakeTimeStamp.o \
    ../../../../../../../mozglue/misc/ConditionVariable_posix.o \
    ../../../../../../../mozglue/misc/MmapFaultHandler.o \
    ../../../../../../../mozglue/misc/Mutex_posix.o \
    ../../../../../../../mozglue/misc/Printf.o \
    ../../../../../../../mozglue/misc/ProcessType.o \
    ../../../../../../../mozglue/misc/RWLock_posix.o \
    ../../../../../../../mozglue/misc/RuntimeExceptionModule.o \
    ../../../../../../../mozglue/misc/SIMD.o \
    ../../../../../../../mozglue/misc/SIMD_avx2.o \
    ../../../../../../../mozglue/misc/SSE.o \
    ../../../../../../../mozglue/misc/StackWalk.o \
    ../../../../../../../mozglue/misc/TimeStamp.o \
    ../../../../../../../mozglue/misc/TimeStamp_posix.o \
    ../../../../../../../mozglue/misc/Uptime.o \
    ../../../../../../../mozglue/misc/Decimal.o \
    ../../../../../../../mfbt/lz4.o \
    ../../../../../../../mfbt/lz4file.o \
    ../../../../../../../mfbt/lz4frame.o \
    ../../../../../../../mfbt/lz4hc.o \
    ../../../../../../../mfbt/xxhash.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt0.o \
    ../../../../../../../mfbt/Unified_cpp_mfbt1.o \
    ../lib/Unified_cpp_unit_tlsserver_lib0.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/alg1485.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certv3.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/certxutl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/crl.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/genname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/polcyxtn.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/secname.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/stanpcertdb.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xauthkid.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xbsconst.o \
    ../../../../../../nss/lib/certdb/certdb_certdb/xconst.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhigh.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certhtml.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certreq.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfy.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/certvfypkix.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/crlv2.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocsp.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/ocspsig.o \
    ../../../../../../nss/lib/certhigh/certhigh_certhi/xcrldist.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/dsautil.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/sechash.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/seckey.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secsign.o \
    ../../../../../../nss/lib/cryptohi/cryptohi_cryptohi/secvfy.o \
    ../../../../../../nss/lib/freebl/freebl_freebl/loader.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixbuild.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixc.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcert.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixcheck.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixder.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnames.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixocsp.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixresult.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixtime.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix/pkixverify.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestalg.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestnss.o \
    ../../../../../../nss/lib/mozpkix/mozpkix_mozpkix-testlib/pkixtestutil.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssinit.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssoptions.o \
    ../../../../../../nss/lib/nss/nss_nss_static/nssver.o \
    ../../../../../../nss/lib/nss/nss_nss_static/utilwrap.o \
    ../../../../../../nss/lib/base/base_nssb/arena.o \
    ../../../../../../nss/lib/base/base_nssb/error.o \
    ../../../../../../nss/lib/base/base_nssb/errorval.o \
    ../../../../../../nss/lib/base/base_nssb/hash.o \
    ../../../../../../nss/lib/base/base_nssb/hashops.o \
    ../../../../../../nss/lib/base/base_nssb/item.o \
    ../../../../../../nss/lib/base/base_nssb/libc.o \
    ../../../../../../nss/lib/base/base_nssb/list.o \
    ../../../../../../nss/lib/base/base_nssb/tracker.o \
    ../../../../../../nss/lib/base/base_nssb/utf8.o \
    ../../../../../../nss/lib/dev/dev_nssdev/ckhelper.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devslot.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devtoken.o \
    ../../../../../../nss/lib/dev/dev_nssdev/devutil.o \
    ../../../../../../nss/lib/pki/pki_nsspki/asymmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certdecode.o \
    ../../../../../../nss/lib/pki/pki_nsspki/certificate.o \
    ../../../../../../nss/lib/pki/pki_nsspki/cryptocontext.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pki3hack.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkibase.o \
    ../../../../../../nss/lib/pki/pki_nsspki/pkistore.o \
    ../../../../../../nss/lib/pki/pki_nsspki/symmkey.o \
    ../../../../../../nss/lib/pki/pki_nsspki/tdcache.o \
    ../../../../../../nss/lib/pki/pki_nsspki/trustdomain.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/dev3hack.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11akey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11auth.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cert.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11cxt.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11err.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11hpke.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11kea.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11list.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11load.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11mech.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11merge.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11nobj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11obj.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pars.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pbe.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pk12.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11pqg.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11sdr.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11skey.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11slot.o \
    ../../../../../../nss/lib/pk11wrap/pk11wrap_pk11wrap/pk11util.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsarray.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsasn1.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsattr.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmscipher.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdecode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsdigest.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsencode.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsenvdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsmessage.o \
    ../../../../../../nss/lib/smime/smime_smime/cmspubkey.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsrecinfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsreclist.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssigdata.o \
    ../../../../../../nss/lib/smime/smime_smime/cmssiginfo.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsudf.o \
    ../../../../../../nss/lib/smime/smime_smime/cmsutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimemessage.o \
    ../../../../../../nss/lib/smime/smime_smime/smimeutil.o \
    ../../../../../../nss/lib/smime/smime_smime/smimever.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/authcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/cmpcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/dtlscon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/prelib.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/selfencrypt.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ecc.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3ext.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssl3gthr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslauth.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslbloom.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcert.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslcon.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssldef.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslencode.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslenum.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerr.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslerrstrs.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslgrp.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinfo.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslinit.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslmutex.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslnonce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslprimitive.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslreveal.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsecur.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsnce.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslsock.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslspec.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/ssltrace.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/sslver.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13con.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13ech.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13echv.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13exthandle.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hashstate.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13hkdf.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13psk.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13replay.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/tls13subcerts.o \
    ../../../../../../nss/lib/ssl/ssl_ssl/unix_err.o
