ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = autoconf-js.mk
include $(DEPTH)/config/emptyvars-js.mk
A11Y_LOG = 1
ACCESSIBILITY = 1
ACDEFINES = -DA11Y_LOG=1 -DACCESSIBILITY=1 -DBUILD_CTYPES=1 -DCROSS_COMPILE='' -DEARLY_BETA_OR_EARLIER=1 -DENABLE_CHANGE_ARRAY_BY_COPY=1 -DENABLE_SHARED_MEMORY=1 -DENABLE_SPIDERMONKEY_TELEMETRY=1 -DENABLE_SYSTEM_EXTENSION_DIRS=1 -DENABLE_TESTS=1 -DENABLE_WASM_AVX=1 -DENABLE_WASM_EXTENDED_CONST=1 -DENABLE_WASM_FUNCTION_REFERENCES=1 -DENABLE_WASM_GC=1 -DENABLE_WASM_MEMORY64=1 -DENABLE_WASM_MOZ_INTGEMM=1 -DENABLE_WASM_RELAXED_SIMD=1 -DENABLE_WASM_SIMD=1 -DENABLE_WASM_TYPE_REFLECTIONS=1 -DENABLE_WEBDRIVER=1 -DFORCE_PR_LOG=1 -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_14 -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_14 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_42 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_42 -DGL_PROVIDER_EGL=1 -DGTEST_HAS_RTTI=0 -DHAVE_64BIT_BUILD=1 -DHAVE_ALLOCA_H=1 -DHAVE_BYTESWAP_H=1 -DHAVE_CLOCK_MONOTONIC=1 -DHAVE_CPUID_H=1 -DHAVE_DIRENT_H=1 -DHAVE_DLADDR=1 -DHAVE_DLOPEN=1 -DHAVE_FTS_H=1 -DHAVE_GETCONTEXT=1 -DHAVE_GETC_UNLOCKED=1 -DHAVE_GETOPT_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LANGINFO_CODESET=1 -DHAVE_LIBM=1 -DHAVE_LINUX_IF_ADDR_H=1 -DHAVE_LINUX_JOYSTICK_H=1 -DHAVE_LINUX_PERF_EVENT_H=1 -DHAVE_LINUX_QUOTA_H=1 -DHAVE_LINUX_RTNETLINK_H=1 -DHAVE_LOCALECONV=1 -DHAVE_LOCALTIME_R=1 -DHAVE_LSTAT64=1 -DHAVE_LUTIMES=1 -DHAVE_MALLINFO=1 -DHAVE_MALLOC_H=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MEMALIGN=1 -DHAVE_NETINET_IN_H=1 -DHAVE_NL_TYPES_H=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_RES_NINIT=1 -DHAVE_SETPRIORITY=1 -DHAVE_SSIZE_T=1 -DHAVE_STAT64=1 -DHAVE_STATFS=1 -DHAVE_STATFS64=1 -DHAVE_STATVFS=1 -DHAVE_STATVFS64=1 -DHAVE_STDINT_H=1 -DHAVE_STRERROR=1 -DHAVE_STRNDUP=1 -DHAVE_SYSCALL=1 -DHAVE_SYS_MOUNT_H=1 -DHAVE_SYS_QUEUE_H=1 -DHAVE_SYS_QUOTA_H=1 -DHAVE_SYS_STATFS_H=1 -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_THREAD_TLS_KEYWORD=1 -DHAVE_TM_ZONE_TM_GMTOFF=1 -DHAVE_TRUNCATE64=1 -DHAVE_UNISTD_H=1 -DHAVE_UNWIND_H=1 -DHAVE_VALLOC=1 -DHAVE_VISIBILITY_ATTRIBUTE=1 -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE=1 -DHAVE__UNWIND_BACKTRACE=1 -DJSON_USE_EXCEPTION=0 -DJS_64BIT=1 -DJS_CODEGEN_X64=1 -DJS_DEFAULT_JITREPORT_GRANULARITY=3 -DJS_HAS_CTYPES=1 -DJS_HAS_INTL_API=1 -DJS_PUNBOX64=1 -DMALLOC_H='<malloc.h>' -DMALLOC_USABLE_SIZE_CONST_PTR='' -DMOZILLA_UAVERSION='"110.0"' -DMOZILLA_VERSION='"110.0a1"' -DMOZILLA_VERSION_U=110.0a1 -DMOZJS_MAJOR_VERSION=110 -DMOZJS_MINOR_VERSION=0 -DMOZ_AARCH64_JSCVT=0 -DMOZ_ACCESSIBILITY_ATK=1 -DMOZ_AUTH_EXTENSION=1 -DMOZ_AV1=1 -DMOZ_BACKGROUNDTASKS=1 -DMOZ_BLOCK_PROFILE_DOWNGRADE=1 -DMOZ_BUILD_APP=browser -DMOZ_BUNDLED_FONTS=1 -DMOZ_CRASHREPORTER=1 -DMOZ_DATA_REPORTING=1 -DMOZ_DAV1D_ASM=1 -DMOZ_DEDICATED_PROFILES=1 -DMOZ_DEMANGLE_SYMBOLS=1 -DMOZ_DIAGNOSTIC_ASSERT_ENABLED=1 -DMOZ_DLL_PREFIX='"lib"' -DMOZ_DLL_SUFFIX='".so"' -DMOZ_DMD=1 -DMOZ_DOM_STREAMS=1 -DMOZ_ENABLE_DBUS=1 -DMOZ_ENABLE_FORKSERVER=1 -DMOZ_ENABLE_SKIA_PDF=1 -DMOZ_FFMPEG=1 -DMOZ_FFVPX=1 -DMOZ_FMP4=1 -DMOZ_GECKO_PROFILER=1 -DMOZ_GECKO_PROFILER_PARSE_ELF=1 -DMOZ_GLUE_IN_PROGRAM=1 -DMOZ_HAS_REMOTE=1 -DMOZ_HAVE_FREETYPE2=1 -DMOZ_INSTRUMENT_EVENT_LOOP=1 -DMOZ_JXL=1 -DMOZ_LIBAV_FFT=1 -DMOZ_LOGGING=1 -DMOZ_MEMORY=1 -DMOZ_NEW_NOTIFICATION_STORE=1 -DMOZ_NEW_XULSTORE=1 -DMOZ_NORMANDY=1 -DMOZ_OXIDIZED_BREAKPAD=1 -DMOZ_PDF_PRINTING=1 -DMOZ_PEERCONNECTION=1 -DMOZ_PLACES=1 -DMOZ_PROFILER_MEMORY=1 -DMOZ_PROFILING=1 -DMOZ_PROXY_DIRECT_FAILOVER=1 -DMOZ_RAW=1 -DMOZ_REAL_TIME_TRACING=1 -DMOZ_REPLACE_MALLOC=1 -DMOZ_SAMPLE_TYPE_FLOAT32=1 -DMOZ_SANDBOX=1 -DMOZ_SCTP=1 -DMOZ_SERVICES_HEALTHREPORT=1 -DMOZ_SRTP=1 -DMOZ_STATIC_JS=1 -DMOZ_TREE_PIXMAN=1 -DMOZ_UPDATER=1 -DMOZ_UPDATE_CHANNEL=default -DMOZ_USER_DIR='".mozilla"' -DMOZ_USING_WASM_SANDBOXING=1 -DMOZ_VERIFY_MAR_SIGNATURE=1 -DMOZ_VORBIS=1 -DMOZ_VTUNE=1 -DMOZ_WASM_SANDBOXING_EXPAT=1 -DMOZ_WASM_SANDBOXING_GRAPHITE=1 -DMOZ_WASM_SANDBOXING_HUNSPELL=1 -DMOZ_WASM_SANDBOXING_OGG=1 -DMOZ_WASM_SANDBOXING_WOFF2=1 -DMOZ_WAYLAND=1 -DMOZ_WEBRTC=1 -DMOZ_WEBRTC_ASSERT_ALWAYS=1 -DMOZ_WEBRTC_SIGNALING=1 -DMOZ_WEBSPEECH=1 -DMOZ_WEBSPEECH_TEST_BACKEND=1 -DMOZ_WIDGET_GTK=1 -DMOZ_X11=1 -DNECKO_WIFI=1 -DNIGHTLY_BUILD=1 -DNO_NSPR_10_SUPPORT=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DSTATIC_JS_API=1 -DSTDC_HEADERS=1 -DUSE_FC_FREETYPE=1 -DU_STATIC_IMPLEMENTATION=1 -DU_USING_ICU_NAMESPACE=0 -DWASM_HAS_HEAPREG=1 -DXP_LINUX=1 -DXP_UNIX=1 -D_REENTRANT=1
ANDROID_PACKAGE_NAME = org.mozilla.firefox
AR = /home/gitpod/.mozbuild/clang/bin/llvm-ar
AR_FLAGS = crs $@
AS = /home/gitpod/.mozbuild/clang/bin/clang --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
ASFLAGS = -fPIC -Wa,--noexecstack
ASOUTOPTION = -o 
AS_DASH_C_FLAG = -c
AWK = /usr/bin/gawk
BINDGEN_SYSTEM_FLAGS = -x c++ -fno-sized-deallocation -fno-aligned-new -DTRACING=1 -DIMPL_LIBXUL -DMOZILLA_INTERNAL_API -DRUST_BINDGEN -DOS_POSIX=1 -DOS_LINUX=1 --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
BUILD_BACKENDS = RecursiveMake FasterMake Clangd
BUILD_CTYPES = 1
CAIRO_FT_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2
CARGO = /home/gitpod/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo
CARGO_INCREMENTAL = 1
CARGO_PROFILE_DEV_OPT_LEVEL = 2
CARGO_PROFILE_RELEASE_OPT_LEVEL = 2
CBINDGEN = /home/gitpod/.mozbuild/cbindgen/cbindgen
CC = /home/gitpod/.mozbuild/clang/bin/clang --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
CC_BASE_FLAGS = --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
CC_TYPE = clang
CC_VERSION = 15.0.5
CLANG_CXX = 1
COLOR_CFLAGS = -fcolor-diagnostics
COMPILE_ENVIRONMENT = 1
CPP = /home/gitpod/.mozbuild/clang/bin/clang -E --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
CPU_ARCH = x86_64
CROSS_LIB = /usr/x86_64-pc-linux-gnu
CXX = /home/gitpod/.mozbuild/clang/bin/clang++ --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
CXXCPP = /home/gitpod/.mozbuild/clang/bin/clang++ -E --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
CXX_BASE_FLAGS = --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
DEVELOPER_OPTIONS = 1
DIST = /workspace/Odyssey/dist
DLL_PREFIX = lib
DLL_SUFFIX = .so
DSO_LDOPTS = -shared -Wl,-z,defs
DUMP_SYMS = /home/gitpod/.mozbuild/dump_syms/dump_syms
EARLY_BETA_OR_EARLIER = 1
ENABLE_CHANGE_ARRAY_BY_COPY = 1
ENABLE_SHARED_MEMORY = 1
ENABLE_TESTS = 1
ENABLE_UNIFIED_BUILD = 1
ENABLE_WASM_AVX = 1
ENABLE_WASM_EXTENDED_CONST = 1
ENABLE_WASM_FUNCTION_REFERENCES = 1
ENABLE_WASM_GC = 1
ENABLE_WASM_MEMORY64 = 1
ENABLE_WASM_MOZ_INTGEMM = 1
ENABLE_WASM_RELAXED_SIMD = 1
ENABLE_WASM_SIMD = 1
ENABLE_WASM_TYPE_REFLECTIONS = 1
ENABLE_WEBDRIVER = 1
EXPAND_LIBS_LIST_STYLE = linkerscript
FFI_TARGET = X86_64
FFI_TARGET_DIR = x86
FFVPX_ASFLAGS = -D__x86_64__ -DPIC -DELF -Pconfig_unix64.asm
FFVPX_USE_NASM = 1
FT2_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lfreetype -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lfontconfig -lfreetype
GCC_USE_GNU_LD = 1
GLIB_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include
GLIB_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lgobject-2.0 -lglib-2.0
GMAKE = /usr/bin/make
GNU_AS = 1
GNU_CC = 1
GNU_CXX = 1
GRE_MILESTONE = 110.0a1
HAVE_64BIT_BUILD = 1
HAVE_CLOCK_MONOTONIC = 1
HAVE_GETCONTEXT = 1
HAVE_INTTYPES_H = 1
HAVE_LANGINFO_CODESET = 1
HAVE_LINUX_PERF_EVENT_H = 1
HG = /home/gitpod/.pyenv/shims/hg
HOST_ALIAS = x86_64-pc-linux-gnu
HOST_AR = /home/gitpod/.mozbuild/clang/bin/llvm-ar
HOST_CC = /home/gitpod/.mozbuild/clang/bin/clang --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
HOST_CC_BASE_FLAGS = --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu99
HOST_CC_TYPE = clang
HOST_CC_VERSION = 15.0.5
HOST_CFLAGS = -DXP_UNIX
HOST_CPU_ARCH = x86_64
HOST_CXX = /home/gitpod/.mozbuild/clang/bin/clang++ --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
HOST_CXX_BASE_FLAGS = --sysroot /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu -Qunused-arguments -std=gnu++17
HOST_DLL_PREFIX = lib
HOST_DLL_SUFFIX = .so
HOST_LDFLAGS =  -fuse-ld=lld -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/lib/x86_64-linux-gnu -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -Wl,-O0
HOST_LIB_PREFIX = lib
HOST_OPTIMIZE_FLAGS = -O3
HOST_OS_ARCH = Linux
INTEL_ARCHITECTURE = 1
IPDL_ROOT = /workspace/Odyssey/ipc/ipdl
JS_CODEGEN_X64 = 1
JS_CONFIG_LIBS = -L/workspace/Odyssey/dist/bin -lnspr4 -lplc4 -lplds4 -lm -ldl 
JS_CONFIG_MOZ_JS_LIBS = -L${libdir} -l${JS_LIBRARY_NAME}
JS_DISABLE_SHELL = 1
JS_HAS_CTYPES = 1
JS_HAS_INTL_API = 1
JS_LIBRARY_NAME = mozjs
L10NBASEDIR = /home/gitpod/.mozbuild/l10n-central
LIBFUZZER_FLAGS = -fsanitize-coverage=trace-pc-guard,trace-cmp
LIBJPEG_TURBO_SIMD_FLAGS = -D__x86_64__ -DPIC -DELF
LIBJPEG_TURBO_USE_NASM = 1
LIB_PREFIX = lib
LIB_SUFFIX = a
LINKER_KIND = lld
LLVM_OBJDUMP = /home/gitpod/.mozbuild/clang/bin/llvm-objdump
LLVM_PROFDATA = /home/gitpod/.mozbuild/clang/bin/llvm-profdata
M4 = /usr/bin/m4
MAKENSISU_FLAGS = -nocd
MKCSHLIB = $(CC) $(COMPUTED_C_LDFLAGS) $(PGO_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MKSHLIB = $(CXX) $(COMPUTED_CXX_LDFLAGS) $(PGO_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MMX_FLAGS = -mmmx
MOZILLA_SYMBOLVERSION = 110a1
MOZILLA_VERSION = 110.0a1
MOZJS_ALPHA = a
MOZJS_MAJOR_VERSION = 110
MOZJS_MINOR_VERSION = 0
MOZJS_PATCH_VERSION = 0
MOZ_ADJUST_SDK_KEY = no-adjust-sdk-key
MOZ_ALSA_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/alsa
MOZ_ALSA_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lasound
MOZ_APP_BASENAME = Firefox
MOZ_APP_NAME = firefox
MOZ_APP_REMOTINGNAME = firefox-default
MOZ_APP_VERSION = 110.0a1
MOZ_APP_VERSION_DISPLAY = 110.0a1
MOZ_AUTH_EXTENSION = 1
MOZ_AV1 = 1
MOZ_BACKGROUNDTASKS = 1
MOZ_BING_API_CLIENTID = no-bing-api-clientid
MOZ_BING_API_KEY = no-bing-api-key
MOZ_BLOCK_PROFILE_DOWNGRADE = 1
MOZ_BUILD_APP = browser
MOZ_BUILD_NSPR = 1
MOZ_CLANG_PATH = /home/gitpod/.mozbuild/clang/bin/clang++
MOZ_CRASHREPORTER = 1
MOZ_CRASHREPORTER_URL = https://crash-reports.mozilla.com
MOZ_DATA_REPORTING = 1
MOZ_DAV1D_ASM = 1
MOZ_DBUS_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/dbus-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/dbus-1.0/include
MOZ_DBUS_GLIB_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/dbus-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include
MOZ_DBUS_GLIB_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0
MOZ_DBUS_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -ldbus-1
MOZ_DEBUG_DEFINES = NDEBUG TRIMMED
MOZ_DEBUG_FLAGS = -gdwarf-4
MOZ_DEBUG_SYMBOLS = 1
MOZ_DEDICATED_PROFILES = 1
MOZ_DIAGNOSTIC_ASSERT_ENABLED = 1
MOZ_DMD = 1
MOZ_DOM_STREAMS = 1
MOZ_EME_MODULES = widevine
MOZ_ENABLE_CAIRO_FT = 1
MOZ_ENABLE_DBUS = 1
MOZ_ENABLE_FORKSERVER = 1
MOZ_ENABLE_SKIA_PDF = 1
MOZ_FFMPEG = 1
MOZ_FFVPX = 1
MOZ_FIX_LINK_PATHS = -Wl,-rpath-link,/workspace/Odyssey/dist/bin -Wl,-rpath-link,/usr/local/lib
MOZ_FMP4 = 1
MOZ_FRAMEPTR_FLAGS = -fno-omit-frame-pointer -funwind-tables
MOZ_GECKODRIVER = 1
MOZ_GECKO_PROFILER = 1
MOZ_GECKO_PROFILER_PARSE_ELF = 1
MOZ_GLUE_IN_PROGRAM = 1
MOZ_GL_DEFAULT_PROVIDER = EGL
MOZ_GOOGLE_LOCATION_SERVICE_API_KEY = no-google-location-service-api-key
MOZ_GOOGLE_SAFEBROWSING_API_KEY = no-google-safebrowsing-api-key
MOZ_GTHREAD_CFLAGS = -pthread -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include
MOZ_GTHREAD_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lgthread-2.0 -pthread -lglib-2.0
MOZ_GTK3_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gtk-3.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pango-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/cairo -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pixman-1 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/libpng12 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gdk-pixbuf-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gio-unix-2.0/ -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/harfbuzz -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/atk-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi2-atk/2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/dbus-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gtk-3.0/unix-print -pthread
MOZ_GTK3_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
MOZ_HARDENING_CFLAGS = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fstack-clash-protection
MOZ_HARDENING_LDFLAGS = -fstack-protector-strong -fstack-clash-protection
MOZ_HAS_REMOTE = 1
MOZ_ICU_VERSION = 72
MOZ_INSTRUMENT_EVENT_LOOP = 1
MOZ_JAR_MAKER_FILE_FORMAT = symlink
MOZ_JXL = 1
MOZ_LEANPLUM_SDK_CLIENTID = no-leanplum-sdk-clientid
MOZ_LEANPLUM_SDK_KEY = no-leanplum-sdk-key
MOZ_LIBAV_FFT = 1
MOZ_LIBCLANG_PATH = /home/gitpod/.mozbuild/clang/lib
MOZ_MEMORY = 1
MOZ_MOZILLA_API_KEY = no-mozilla-api-key
MOZ_NEW_NOTIFICATION_STORE = 1
MOZ_NEW_XULSTORE = 1
MOZ_NORMANDY = 1
MOZ_NO_DEBUG_RTL = 1
MOZ_OPTIMIZE = 1
MOZ_OPTIMIZE_FLAGS = -O3
MOZ_OXIDIZED_BREAKPAD = 1
MOZ_PACKAGER_FORMAT = omni
MOZ_PACKAGER_MINIFY = 1
MOZ_PANGO_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pango-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -pthread
MOZ_PANGO_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lpango-1.0 -lgobject-2.0 -lglib-2.0
MOZ_PDF_PRINTING = 1
MOZ_PEERCONNECTION = 1
MOZ_PGO_OPTIMIZE_FLAGS = -O3
MOZ_PHC = 1
MOZ_PLACES = 1
MOZ_POCKET_API_KEY = no-pocket-api-key
MOZ_PREF_EXTENSIONS = 1
MOZ_PROFILER_MEMORY = 1
MOZ_PROFILING = 1
MOZ_PROGRAM_LDFLAGS =  -pie
MOZ_PROXY_DIRECT_FAILOVER = 1
MOZ_PULSEAUDIO = 1
MOZ_PULSEAUDIO_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -D_REENTRANT
MOZ_PULSEAUDIO_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lpulse
MOZ_RAW = 1
MOZ_REAL_TIME_TRACING = 1
MOZ_REPLACE_MALLOC = 1
MOZ_REPLACE_MALLOC_STATIC = 1
MOZ_RUST_DEFAULT_FLAGS = -C debuginfo=2 -C force-frame-pointers=yes --cap-lints warn
MOZ_SAMPLE_TYPE_FLOAT32 = 1
MOZ_SANDBOX = 1
MOZ_SCTP = 1
MOZ_SERVICES_HEALTHREPORT = 1
MOZ_SERVICES_SYNC = 1
MOZ_SRTP = 1
MOZ_SYNTH_SPEECHD = 1
MOZ_SYSTEM_POLICIES = 1
MOZ_TREE_PIXMAN = 1
MOZ_TRIVIAL_AUTO_VAR_INIT = -ftrivial-auto-var-init=pattern
MOZ_UI_LOCALE = en-US
MOZ_UNIVERSALCHARDET = 1
MOZ_UPDATER = 1
MOZ_UPDATE_CHANNEL = default
MOZ_USING_WASM_SANDBOXING = 1
MOZ_VERIFY_MAR_SIGNATURE = 1
MOZ_VORBIS = 1
MOZ_VTUNE = 1
MOZ_WASM_SANDBOXING_EXPAT = 1
MOZ_WASM_SANDBOXING_GRAPHITE = 1
MOZ_WASM_SANDBOXING_HUNSPELL = 1
MOZ_WASM_SANDBOXING_OGG = 1
MOZ_WASM_SANDBOXING_WOFF2 = 1
MOZ_WAYLAND = 1
MOZ_WAYLAND_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gtk-3.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pango-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/glib-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/cairo -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/pixman-1 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/libpng12 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gdk-pixbuf-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/gio-unix-2.0/ -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/harfbuzz -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/atk-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi2-atk/2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/at-spi-2.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/dbus-1.0 -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/libdrm
MOZ_WAYLAND_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lxkbcommon -ldrm
MOZ_WEBEXT_WEBIDL_ENABLED = 1
MOZ_WEBMIDI_MIDIR_IMPL = 1
MOZ_WEBRTC = 1
MOZ_WEBRTC_ASSERT_ALWAYS = 1
MOZ_WEBRTC_HAVE_ETHTOOL_SPEED_HI = 1
MOZ_WEBRTC_SIGNALING = 1
MOZ_WEBSPEECH = 1
MOZ_WEBSPEECH_TEST_BACKEND = 1
MOZ_WIDGET_TOOLKIT = gtk
MOZ_X11 = 1
MOZ_X11_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include
MOZ_X11_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lxcb-shm -lX11-xcb -lX11 -lxcb -lXext -lXrandr -lXcomposite -lXcursor -lXdamage -lXfixes -lXi -lXtst
MOZ_X11_SM_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include
MOZ_ZIPWRITER = 1
NASM = /home/gitpod/.mozbuild/nasm/nasm
NASM_ASFLAGS = -f elf64
NECKO_WIFI = 1
NECKO_WIFI_DBUS = 1
NIGHTLY_BUILD = 1
NM = /home/gitpod/.mozbuild/clang/bin/llvm-nm
NODEJS = /home/gitpod/.mozbuild/node/bin/node
NSPR_CFLAGS = -I/workspace/Odyssey/dist/include/nspr
NSPR_INCLUDE_DIR = /workspace/Odyssey/dist/include/nspr
NSPR_LIBS = -L/workspace/Odyssey/dist/bin -lnspr4 -lplc4 -lplds4
NSPR_LIB_DIR = /workspace/Odyssey/dist/bin
NSS_CFLAGS = -I/workspace/Odyssey/dist/include/nss
NS_PRINTING = 1
OBJCOPY = /home/gitpod/.mozbuild/clang/bin/llvm-objcopy
OBJ_SUFFIX = o
OMNIJAR_NAME = omni.ja
OS_ARCH = Linux
OS_CFLAGS = -fPIC -fno-math-errno -pthread -pipe
OS_COMPILE_CFLAGS = -include /workspace/Odyssey/js/src/js-confdefs.h -DMOZILLA_CLIENT
OS_COMPILE_CXXFLAGS = -DMOZILLA_CLIENT -include /workspace/Odyssey/js/src/js-confdefs.h
OS_CXXFLAGS = -fno-sized-deallocation -fno-aligned-new -fPIC -fno-rtti -fno-exceptions -fno-math-errno -pthread -pipe
OS_LDFLAGS = -lpthread -fuse-ld=lld -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/lib/x86_64-linux-gnu -Wl,-rpath-link,/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -Wl,-O0 -Wl,-z,noexecstack -Wl,-z,text -Wl,-z,relro -Wl,-z,nocopyreloc -Wl,-Bsymbolic-functions
OS_LIBS = -lm -ldl 
OS_TARGET = Linux
PATH = /home/gitpod/.pyenv/versions/3.8.13/bin:/home/gitpod/.pyenv/libexec:/home/gitpod/.pyenv/plugins/python-build/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/bin:/home/gitpod/.pyenv/plugins/pyenv-update/bin:/home/gitpod/.pyenv/plugins/pyenv-installer/bin:/home/gitpod/.pyenv/plugins/pyenv-doctor/bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/workspace/.cargo/bin:/home/gitpod/.rvm/gems/ruby-3.1.2/bin:/home/gitpod/.rvm/gems/ruby-3.1.2@global/bin:/home/gitpod/.rvm/rubies/ruby-3.1.2/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/.nix-profile/bin:/ide/bin/remote-cli:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/home/gitpod/.nvm/versions/node/v16.19.0/bin:/home/gitpod/.yarn/bin:/home/gitpod/.pnpm:/home/gitpod/.pyenv/bin:/workspace/.rvm/bin:/home/gitpod/.cargo/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.local/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/gitpod/.nvm/versions/node/v16.19.0/bin:/home/gitpod/.rvm/bin:/workspace/Odyssey/scriptsdepot_tools:/workspace/Odyssey/scripts/depot_tools
PERL = /usr/bin/perl
PGO_PROFILE_PATH = /workspace/Odyssey/instrumented/merged.profdata
PKG_CONFIG = /home/gitpod/.mozbuild/pkgconf/pkg-config
PKG_CONFIG_LIBDIR = /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/pkgconfig:/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu/pkgconfig:/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/share/pkgconfig
PKG_CONFIG_SYSROOT_DIR = /home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu
PKG_STRIP = 1
PREPROCESS_OPTION = -E -o 
PROFILE_GEN_CFLAGS = -fprofile-generate
PROFILE_GEN_LDFLAGS = -fprofile-generate
PROFILE_USE_CFLAGS = -fprofile-use=/workspace/Odyssey/instrumented/merged.profdata -Wno-error=backend-plugin
PYTHON3 = /workspace/Odyssey/_virtualenvs/build/bin/python
PYTHON3_VERSION = 3.8.13
READELF = /home/gitpod/.mozbuild/clang/bin/llvm-readelf
RPMBUILD = /usr/bin/rpmbuild
RUSTC = /home/gitpod/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc
RUSTC_COMMIT = 897e37553bba8b42751c67658967889d11ecd120
RUSTC_LLVM_VERSION = 15.0.0
RUSTC_VERSION = 1.65.0
RUSTDOC = /home/gitpod/.cargo/bin/rustdoc
RUSTFMT = /home/gitpod/.cargo/bin/rustfmt
RUST_HOST_TARGET = x86_64-unknown-linux-gnu
RUST_TARGET = x86_64-unknown-linux-gnu
SHELL = /bin/sh
SKIA_INCLUDES = /gfx/skia /gfx/skia/skia
SSE2_FLAGS = -msse2
SSE_FLAGS = -msse
SSSE3_FLAGS = -mssse3
STRIP = /home/gitpod/.mozbuild/clang/bin/llvm-strip
STRIP_FLAGS = --strip-debug
TAR = /usr/bin/tar
TARGET_CPU = x86_64
TARGET_ENDIANNESS = little
TARGET_OS = linux-gnu
TARGET_XPCOM_ABI = x86_64-gcc3
UNZIP = /usr/bin/unzip
VCS_CHECKOUT_TYPE = hg
VISIBILITY_FLAGS = -I/workspace/Odyssey/dist/system_wrappers -include /workspace/Odyssey/src/config/gcc_hidden.h
VPX_USE_NASM = 1
WARNINGS_CFLAGS = -Wall -Wbitfield-enum-conversion -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wclass-varargs -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wenum-compare-conditional -Wenum-float-conversion -Wstring-conversion -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Werror=implicit-function-declaration -Wno-psabi -Wthread-safety -Wno-unknown-warning-option
WARNINGS_CXXFLAGS = -Wall -Wbitfield-enum-conversion -Wdeprecated-this-capture -Wempty-body -Wformat-type-confusion -Wignored-qualifiers -Wpointer-arith -Wshadow-field-in-constructor-modified -Wsign-compare -Wtype-limits -Wno-error=tautological-type-limit-compare -Wunreachable-code -Wunreachable-code-return -Wunused-but-set-parameter -Wno-invalid-offsetof -Wclass-varargs -Wempty-init-stmt -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wloop-analysis -Wno-range-loop-analysis -Wc++2a-compat -Wenum-compare-conditional -Wenum-float-conversion -Wno-ambiguous-reversed-operator -Wno-error=deprecated -Wno-error=deprecated-anon-enum-enum-conversion -Wno-error=deprecated-enum-enum-conversion -Wno-error=deprecated-pragma -Wno-error=deprecated-this-capture -Wcomma -Wimplicit-fallthrough -Wstring-conversion -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wno-error=free-nonheap-object -Wno-error=atomic-alignment -Wno-error=deprecated-builtins -Wformat -Wformat-security -Wno-psabi -Wthread-safety -Wno-unknown-warning-option
WASI_SYSROOT = /home/gitpod/.mozbuild/sysroot-wasm32-wasi
WASM_CC = /home/gitpod/.mozbuild/clang/bin/clang -Qunused-arguments -std=gnu99 --target=wasm32-wasi --sysroot=/home/gitpod/.mozbuild/sysroot-wasm32-wasi
WASM_CC_BASE_FLAGS = -Qunused-arguments -std=gnu99 --target=wasm32-wasi
WASM_CC_TYPE = clang
WASM_CC_VERSION = 15.0.5
WASM_CFLAGS = -fno-exceptions -fno-strict-aliasing
WASM_CXX = /home/gitpod/.mozbuild/clang/bin/clang++ -Qunused-arguments -std=gnu++17 --target=wasm32-wasi --sysroot=/home/gitpod/.mozbuild/sysroot-wasm32-wasi
WASM_CXXFLAGS = -fno-exceptions -fno-strict-aliasing
WASM_CXX_BASE_FLAGS = -Qunused-arguments -std=gnu++17 --target=wasm32-wasi
WASM_OBJ_SUFFIX = wasm
WEBIDL_ROOT = /workspace/Odyssey/dom/bindings
WGET = /usr/bin/wget
WRAP_SYSTEM_INCLUDES = 1
XARGS = /usr/bin/xargs
XPCOM_ROOT = /workspace/Odyssey/xpcom/components
_AS = /home/gitpod/.mozbuild/clang/bin/clang
_CARGO = /home/gitpod/.cargo/bin/cargo
_CC = /home/gitpod/.mozbuild/clang/bin/clang
_CXX = /home/gitpod/.mozbuild/clang/bin/clang++
_DEPEND_CFLAGS = -MD -MP -MF $(MDDEPDIR)/$(@F).pp
_FONTCONFIG_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2
_FONTCONFIG_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lfontconfig -lfreetype
_FT2_CFLAGS = -I/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/include/freetype2
_FT2_LIBS = -L/home/gitpod/.mozbuild/sysroot-x86_64-linux-gnu/usr/lib/x86_64-linux-gnu -lfreetype
_HOST_CC = /home/gitpod/.mozbuild/clang/bin/clang
_HOST_CXX = /home/gitpod/.mozbuild/clang/bin/clang++
_HOST_DEPEND_CFLAGS = -MD -MP -MF $(MDDEPDIR)/$(@F).pp
_RUSTC = /home/gitpod/.cargo/bin/rustc
_WASM_CC = /home/gitpod/.mozbuild/clang/bin/clang
_WASM_CXX = /home/gitpod/.mozbuild/clang/bin/clang++
autoconfmk = autoconf-js.mk
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-pc-linux-gnu
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = x86_64-pc-linux-gnu
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = x86_64-pc-linux-gnu
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_srcdir = /workspace/Odyssey/src/js/src/../..
include $(topsrcdir)/config/baseconfig.mk
endif
